[settings]
experimental = true
pipx_uvx = true

[tools]
java = "latest"
terraform = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "lts"
python = "3.13"
rust = "latest"

ghq = "latest"
fzf = "latest"
awscli = "latest"
tfenv = "latest"
jq = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
bat = "latest"
"pipx:snowflake-cli" = "latest"
